<?if($this->updateNotice):?>
    <?$this->headScript()->captureStart()?>
        kkcms.effect.setOptions({image: "<?=$this->imgUrl('admin/info-update.png')?>"})
            .message("<?=$this->lng->_js('MSG_ADMIN_INDEX_UPDATES_AVAILABLE')?>");
    <?$this->headScript()->captureEnd()?>
<?endif?>

<?if (count($this->defaultModules)):?>
    <div class="page-title">
        <h1><?=$this->lng->_('LBL_ADMIN_INDEX_NAV_MAIN')?></h1>
        <p><?=$this->lng->_('TXT_ADMIN_INDEX_NAV_MAIN_DESCR')?></p>
    </div>

    <div class="page-content">
        <div class='admin-nav cleared'>
            <?foreach ($this->defaultModules as $module):?>
                <a class='cornered' href="/open/admin-<?=$module?>/"
                    style="background-image: url('<?=$this->imgUrl("admin/main/mdl-{$module}.png")?>');">
                    <?=$this->lng->_('LBL_ADMIN_' . strtoupper($module))?>
                </a>
            <?endforeach?>
        </div>
    </div>
<?endif?>

<?if (count($this->advancedModules)):?>
    <div class="page-title">
        <h2><?=$this->lng->_('LBL_ADMIN_INDEX_NAV_ADV')?></h2>
        <p><?=$this->lng->_('TXT_ADMIN_INDEX_NAV_ADV_DESCR')?></p>
    </div>

    <div class="page-content">
        <div class='admin-nav cleared'>
            <?foreach ($this->advancedModules as $m):?>
                <a class='cornered' href="/open/admin-<?=$m?>/" style="background-image: url('<?=$this->imgUrl("admin/main/mdl-{$m}.png")?>');">
                    <?=$this->lng->_('LBL_ADMIN_' . strtoupper($m))?>
                </a>
            <?endforeach?>
        </div>
    </div>
<?endif?>

<?if($this->user->hasAcl(CMS_ACCESS_LOGS_VIEW)):?>
    <div class="page-title">
        <h3><?=$this->lng->_('LBL_ADMIN_LOGS')?></h3>
        <p><?=$this->lng->_('TXT_ADMIN_LOGS_DESCR')?></p>
    </div>

    <div class="page-content">
        <table class='cnt-table'>
            <thead>
                <tr>
                    <th style='width:15%'>
                        <?=$this->htmlSort(
                            $this->lng->_('LBL_ADMIN_LOGS_ACCOUNT'),
                            "/open/admin-index/?logpage={$this->input->logpage}", 'account')?>
                    </th>
                    <th style='width:50%'>
                        <?=$this->htmlSort(
                            $this->lng->_('LBL_ADMIN_LOGS_ACTION'),
                            "/open/admin-index/?logpage={$this->input->logpage}", 'action')?>
                    </th>
                    <th style='width:20%'>
                        <?=$this->htmlSort(
                            $this->lng->_('LBL_ADMIN_LOGS_TIME'),
                            "/open/admin-index/?logpage={$this->input->logpage}&amp;sorttype=number", 'time')?>
                    </th>
                    <th style='width:15%'>
                        <?=$this->htmlSort(
                            $this->lng->_('LBL_ADMIN_LOGS_IP'),
                            "/open/admin-index/?logpage={$this->input->logpage}&amp;sorttype=number", 'ip')?>
                    </th>
                </tr>
            </thead>

            <?foreach ($this->logPaginator as $v):?>
                <tr>
                    <td class='center top' style='white-space: nowrap; overflow: hidden;'>
                        <?=($v['name'] ? $v['name'] : '---')?>
                    </td>
                    <td>
                        <?if(strpos($v['text'], '|') !== false):?>
                            <?$log = explode('|', $v['text'])?>
                            <?$log[0] = $this->lng->_($log[0])?>
                            <?=call_user_func_array('sprintf', $log)?>
                        <?else:?>
                            <?=$this->lng->_($v['text'])?>
                        <?endif?>
                    </td>
                    <td class="center top"><?=$this->timeStamp($v['time'], Cms_Date::DATETIME_SHORT)?></td>
                    <td class="center top"><?=$v['ip']?></td>
                </tr>
            <?endforeach?>
        </table>

        <?=$this->paginationControl(
            $this->logPaginator, null, null,
            array(
                'url' => "/open/admin-index/?sortby={$this->input->sortby}&amp;sorttype={$this->input->sorttype}&amp;sortway={$this->input->sortway}&amp;logpage=",
                'lng' => $this->lng
            )
        )?>

    </div>
<?endif?>

<?if($this->checkForUpdate):?>
    <?$this->headScript()->captureStart()?>
        jQuery(document).ready(function() {
            kkcms.ajaxCall(
                '/open/admin-update/',
                {'action':'checknow'},
                function(json) {
                    if (json.success) {
                        kkcms.effect.message(json.data.msg);
                    }
                }
            );
        });
    <?$this->headScript()->captureEnd()?>
<?endif?>

