<div id='inner'>
    <div id='logo-box' class="shifted cleared">
        <div class="navigation">
            <ul class="cleared">
                <li class="story"><a href="/story.html" class="layer<?if(strpos($_SERVER['REQUEST_URI'], 'story.html') !== false):?> active<?endif?>">&nbsp;</a></li>
                <li class="propaganda"><a href="/propaganda.html" class="layer<?if(strpos($_SERVER['REQUEST_URI'], 'propaganda.html') !== false):?> active<?endif?>">&nbsp;</a></li>
                <li class="gallery"><a href="/gallery.html" class="layer<?if(strpos($_SERVER['REQUEST_URI'], 'gallery.html') !== false):?> active<?endif?>">&nbsp;</a></li>
                <li class="next"><a href="/next10.html" class="layer<?if(strpos($_SERVER['REQUEST_URI'], 'next10.html') !== false):?> active<?endif?>">&nbsp;</a></li>
                <li class="contact last"><a href="/contacts.html" class="layer<?if(strpos($_SERVER['REQUEST_URI'], 'contacts.html') !== false):?> active<?endif?>">&nbsp;</a></li>
            </ul>
            <div class="noise layer left">&nbsp;</div>
            <div class="noise layer bottom">&nbsp;</div>
            <div class="noise layer right">&nbsp;</div>
        </div>
        <div class="logo">
            <a href="/" class="layer"></a>
        </div>
    </div>
    <div class="layer box-corner"></div>

    <div id='inner-first' class="topshadow"></div>
    <div id='inner-white'></div>
    <div id='inner-second' class="topshadow"></div>
</div>
