<table width="550" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td align="left" bgcolor="#ffffff">
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td style="border:1px solid #a9d19a;">

						<table border="0" cellspacing="0" cellpadding="0">
							<tr>
								<td style="padding:20px 40px 20px 15px;">
									<table border="0" cellspacing="0" cellpadding="0">
										<tr>
											<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#000000; line-height:20px;" valign="top">
												<p style="margin:0 0 10px 0; font-size:16px; color:#0165ab;"><b style="color:#4ea12d;"><?=$this->title?></b></p>
												<p style="margin:0 0 15px 0;">
													<?=$this->message?>
												</p>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>

						<table style="background-color:#f6faf4; border-top:1px solid #cce4c3;" width="100%" border="0" cellspacing="0" cellpadding="0">
							<tr>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#484848; line-height:17px; padding:15px;" valign="middle">
									&nbsp;
								</td>
							</tr>
						</table>

					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>