<?$this->headTitle(
    empty($this->entry['metadata']['title']) ? $this->entry['title'] : $this->entry['metadata']['title']
)?>

<?$pager = $this->paginationControl(
    $this->paginator, null, 'pager-denza.phtml',
    array('url' => "/propaganda.html?page=", 'lng' => $this->lng)
)?>

<div id='white-area' style="padding: 4px">
    <div id='white-area-content'>

        <?=$pager?>

        <div id='blog'>
            <?$i = 0?>

            <div class='entries'>
                <?foreach ($this->paginator as $entry):?>
                    <?php
                        $parser = new Cms_Text_Parser($entry->getContent());
                        $text = $parser->getText();
                    ?>

                    <?$this->headTitle($entry->title)?>

                    <div class="entry cleared <?=($i == 0 ) ? ' first' : ''?>">
                        <?=$text?>
                        <?if ($parser->getPartsCount() > 1):?>
                            <?=$this->staticPaginator(
                                $parser->getPartsCount(), $parser->getPartNumber(),
                                "/{$entry->getRewrite()}.html?"
                            )?>
                        <?endif?>

                        <?=$this->social(CMS_HOST . "/{$entry->rewrite}.html")?>
                    </div>

                    <?if ($i++ < $this->paginator->count() - 1):?>
                        <hr class="blog" />
                    <?endif?>
                <?endforeach?>
            </div>

            <span class="noise top-left-symbol">&nbsp;</span>
            <span class="noise top-right-symbol">&nbsp;</span>
            <span class="noise bottom-left-symbol">&nbsp;</span>
            <span class="noise bottom-right-symbol">&nbsp;</span>
        </div>
    </div>
</div>
