<?if(!empty($this->input->deny) &&
     in_array($this->input->deny, array('banned', 'blocked', 'wrong'))):?>
    <p><?=$this->lng->_('MSG_SITE_AUTH_' . strtoupper($this->input->deny))?></p>
<?endif?>

<form method='post' action='/open/auth/' id='cms-admin-auth' class='cms-cornered cms-shadow'>

    <input type="hidden" name="referer" value="<?=$this->input->referer?>" />

    <fieldset>
        <div>
            <p>
                <label for="email">E-mail:</label>
                <input type='text' id="email" name='email' value='' maxlength="50" />
            </p>
            <p>
                <label for="password">Password:</label>
                <input type='password' id="password" name='password' value='' maxlength="31" />
            </p>
        </div>

        <p>
            <input type='submit' value="<?=$this->lng->_('LBL_SITE_AUTH_LOGIN')?>" />
            <input type='submit' name="cms_redirect_to_admin" value="<?=$this->lng->_('LBL_SITE_AUTH_GO_ADMIN')?>" />
        </p>
    </fieldset>

    <?if ($this->config->cms->security->auth->level != 'none'):?>
        <p><?=sprintf($this->lng->_('MSG_SITE_AUTH_NOTICE'), Cms_Session::getInstance()->loginAttemp)?></p>
    <?endif?>

</form>
