<?$this->headTitle(
    empty($this->entry['metadata']['title']) ? $this->entry['title'] : $this->entry['metadata']['title']
)?>

<h1><small>+</small><?=!isset($this->customTitle) ? $this->entry['title'] : $this->customTitle?></h1>

<div id='white-area' style="padding: 4px">
    <div id='white-area-content'>

        <div id='page-nav' class="cleared">
            <p>
                <?if (strpos($this->entry['tags'], 'propaganda') !== false):?>
                    <strong><a href='/propaganda.html'>Back to the list</a></strong>
                    <a href='/propaganda.html' class="layer arrow-left">&nbsp;</a>
                <?else:?>
                    <strong><a href='/'>Go to 10denza</a></strong>
                    <a href='/' class="layer arrow-left">&nbsp;</a>
                <?endif?>
            </p>
        </div>

        <div id='page'>
            <?=$this->entry['content']?>

            <span class="noise top-left-symbol">&nbsp;</span>
            <span class="noise top-right-symbol">&nbsp;</span>
            <span class="noise bottom-left-symbol">&nbsp;</span>
            <span class="noise bottom-right-symbol">&nbsp;</span>
        </div>
    </div>
</div>

<?=$this->placeholder('pageDetails')?>

<?=$this->placeholder('pageAdmin')?>
