<?$this->headTitle(
    empty($this->entry['metadata']['title']) ? $this->entry['title'] : $this->entry['metadata']['title']
)?>

<h1><small>+</small><?=!isset($this->customTitle) ? $this->entry['title'] : $this->customTitle?></h1>

<div id='white-area'>
    <div id='white-area-content'>
        <?=$this->entry['content']?>

        <div class='cleared'>
            <?=$this->placeholder('pageDetails')?>
            <?=$this->placeholder('pageAdmin')?>
        </div>
    </div>

    <span class="noise top-left-symbol">&nbsp;</span>
    <span class="noise top-right-symbol">&nbsp;</span>
    <span class="noise bottom-left-symbol">&nbsp;</span>
    <span class="noise bottom-right-symbol">&nbsp;</span>
</div>
